config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  
  get "search" => "searches#search"

  devise_for :users #先に書く
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment,presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    # redirect_to book_path(book)
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    # redirect_to book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<!--コメント機能-->
<div>
  <% book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image,size:'100x100' %><%= book_comment.comment %>
  <!--コメント削除機能-->
    <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
<!--book_book_comments DELETE /books/:book_id/book_comments(.:format)       book_comments#destroy-->
    <% end %>
    </p>
    <%= link_to  book_comment.user.name, book_path(book) %>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$('#comments_<%= @book.id %>').html("<%= j(render "book_comments/comments", book: @book) %>");

app/views/book_comments/destroy.js.erb
$('#comments_<%= @book.id %>').html("<%= j(render "book_comments/comments", book: @book) %>");